# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Research
    pageRef: /research
    weight: 10
  - name: People
    pageRef: /people
    weight: 20
  - name: Publications
    pageRef: /publication
    weight: 30
  - name: Software
    pageRef: /software
    weight: 40
  - name: News
    pageRef: /post
    weight: 50
  - name: Teaching
    pageRef: /teaching
    weight: 60
